# http://travis-ci.org/#!/SpectoLabs/mirage
language: python

cache: pip

python:
    - 2.7

install:
    - travis_retry pip install coveralls
    - travis_retry pip install -r requirements/development.txt

services:
  - redis-server
  - mongodb

# command to run tests
script: 
  - export STUBO_CONFIG_FILE_PATH=./dev.ini
  - nosetests stubo --with-coverage --cover-package=stubo
  
after_success:
    coveralls  
